// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9OnHQVh14lt18fqnTvKESfVEJLQhoE8',
    appId: '1:237664734071:web:cbff07a01536c211472f72',
    messagingSenderId: '237664734071',
    projectId: 'chat-app-41294',
    authDomain: 'chat-app-41294.firebaseapp.com',
    storageBucket: 'chat-app-41294.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIr38Gy5YN7WTRJVVen-aabY5i9k69Nsc',
    appId: '1:237664734071:android:eb68e16a4d277fe4472f72',
    messagingSenderId: '237664734071',
    projectId: 'chat-app-41294',
    storageBucket: 'chat-app-41294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwX1qOQv6CZMYaBfyPLFTCsH4EaErcn-Q',
    appId: '1:237664734071:ios:7282bd26763443e1472f72',
    messagingSenderId: '237664734071',
    projectId: 'chat-app-41294',
    storageBucket: 'chat-app-41294.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwX1qOQv6CZMYaBfyPLFTCsH4EaErcn-Q',
    appId: '1:237664734071:ios:7282bd26763443e1472f72',
    messagingSenderId: '237664734071',
    projectId: 'chat-app-41294',
    storageBucket: 'chat-app-41294.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
